/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CONTROL.departmentController;
import CONTROL.employeeController;
import CONTROL.loginController;
import MODEL.departmentModel;
import MODEL.employeeModel;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vuduc
 */
public class homepageForm extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    List<departmentModel> ListRoom = new ArrayList<>();
    List<employeeModel> ListEmployee = new ArrayList<>();
    String role;

    /**
     * Creates new form Main
     *
     * @param username
     */
    public homepageForm(String username) {
        initComponents();
        setLocationRelativeTo(null);
        rightPanel.setBackground(Color.WHITE);
        tab1.setBackground(Color.gray);
        jb1.setVisible(true);
        jb2.setVisible(false);
        jb3.setVisible(false);
        jb4.setVisible(false);
        jb5.setVisible(false);
        jb6.setVisible(false);
        jbAddEmployee.setVisible(false);
        try {
            loginController getUser = new loginController();
            ResultSet rs = getUser.getInfoUser(username);
            if (rs.next()) {
                edtUsernameHome.setText(rs.getString("username"));
                edtManv.setText(rs.getString("manv"));
                edtUsernameInfo.setText(rs.getString("username"));
                edtRoleInfo.setText(rs.getString("role"));
                edtPosition.setText(rs.getString("position"));
                edtMaphong.setText(rs.getString("maphong"));
                edtMahs.setText(rs.getString("mahoso"));
                role = rs.getString("role");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private homepageForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        leftPanel = new javax.swing.JPanel();
        Avatar = new javax.swing.JPanel();
        AvatarImg = new javax.swing.JLabel();
        edtUsernameHome = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLable8 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLable14 = new javax.swing.JLabel();
        tab1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLable4 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        Notice = new javax.swing.JPanel();
        btn_Logout = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        jb5 = new javax.swing.JPanel();
        AvatarImg1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        edtUsernameInfo = new javax.swing.JLabel();
        edtRoleInfo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        edtPosition = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        edtMaphong = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        edtMahs = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        edtManv = new javax.swing.JLabel();
        jb1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jb2 = new javax.swing.JPanel();
        jbTableRoom = new javax.swing.JScrollPane();
        jtableRoom = new javax.swing.JTable();
        edtSearchRoom = new javax.swing.JTextField();
        btnSearchDepartment = new javax.swing.JButton();
        btnAddRoom = new javax.swing.JButton();
        btnDeleteRoom = new javax.swing.JButton();
        btnUpdateRoom = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jb3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jb4 = new javax.swing.JPanel();
        jb6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmployee = new javax.swing.JTable();
        btnAddEmployee = new javax.swing.JButton();
        btnXoaEmployee = new javax.swing.JButton();
        btnUpdateEmployee = new javax.swing.JButton();
        edtSearchEmployee = new javax.swing.JTextField();
        btnSearchEmployee = new javax.swing.JButton();
        jbAddEmployee = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        edtManvEmployee = new javax.swing.JTextField();
        edtFullName = new javax.swing.JTextField();
        edtBirthday = new javax.swing.JTextField();
        edtPhone = new javax.swing.JTextField();
        edtAddress = new javax.swing.JTextField();
        edtPositionEmployee = new javax.swing.JTextField();
        edtMaphongEmployee = new javax.swing.JTextField();
        edtMahsEmployee = new javax.swing.JTextField();
        jRadioNam = new javax.swing.JRadioButton();
        jRadioNu = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));

        leftPanel.setBackground(new java.awt.Color(102, 102, 102));
        leftPanel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        leftPanel.setPreferredSize(new java.awt.Dimension(340, 164));

        Avatar.setBackground(new java.awt.Color(102, 102, 102));
        Avatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AvatarMouseClicked(evt);
            }
        });

        AvatarImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/Icons/icons8_male_user_120px.png"))); // NOI18N

        edtUsernameHome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        edtUsernameHome.setForeground(new java.awt.Color(255, 255, 255));
        edtUsernameHome.setText("name");

        javax.swing.GroupLayout AvatarLayout = new javax.swing.GroupLayout(Avatar);
        Avatar.setLayout(AvatarLayout);
        AvatarLayout.setHorizontalGroup(
            AvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AvatarLayout.createSequentialGroup()
                .addGroup(AvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AvatarImg)
                    .addGroup(AvatarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(edtUsernameHome)))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        AvatarLayout.setVerticalGroup(
            AvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AvatarLayout.createSequentialGroup()
                .addComponent(AvatarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edtUsernameHome))
        );

        tab2.setBackground(new java.awt.Color(102, 102, 102));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/Icons/icons8_teacher_50px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phòng Ban");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tab3.setBackground(new java.awt.Color(102, 102, 102));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/Icons/icons8_student_male_50px.png"))); // NOI18N

        jLable8.setBackground(new java.awt.Color(102, 102, 102));
        jLable8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLable8.setForeground(new java.awt.Color(255, 255, 255));
        jLable8.setText("Nhân Viên");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLable8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLable8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tab4.setBackground(new java.awt.Color(102, 102, 102));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/Icons/icons8_alarm_50px.png"))); // NOI18N

        jLable14.setBackground(new java.awt.Color(102, 102, 102));
        jLable14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLable14.setForeground(new java.awt.Color(255, 255, 255));
        jLable14.setText("Cài Đặt");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLable14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLable14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tab1.setBackground(new java.awt.Color(102, 102, 102));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/Icons/icons8_monitor_50px_1.png"))); // NOI18N

        jLable4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLable4.setForeground(new java.awt.Color(255, 255, 255));
        jLable4.setText("Trang Chủ");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLable4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLable4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        logout.setBackground(new java.awt.Color(102, 102, 102));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        Notice.setBackground(new java.awt.Color(102, 102, 102));

        btn_Logout.setBackground(new java.awt.Color(0, 153, 204));
        btn_Logout.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setBackground(new java.awt.Color(0, 102, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Logout");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_LogoutLayout = new javax.swing.GroupLayout(btn_Logout);
        btn_Logout.setLayout(btn_LogoutLayout);
        btn_LogoutLayout.setHorizontalGroup(
            btn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_LogoutLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(45, 45, 45))
        );
        btn_LogoutLayout.setVerticalGroup(
            btn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout NoticeLayout = new javax.swing.GroupLayout(Notice);
        Notice.setLayout(NoticeLayout);
        NoticeLayout.setHorizontalGroup(
            NoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoticeLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NoticeLayout.setVerticalGroup(
            NoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoticeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Notice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(Notice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightPanel.setBackground(new java.awt.Color(153, 255, 102));

        jb5.setBackground(new java.awt.Color(153, 153, 255));

        AvatarImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/Icons/icons8_male_user_120px.png"))); // NOI18N

        jLabel6.setText("EDIT");

        jLabel8.setText("Username");

        jLabel9.setText("Role");

        edtUsernameInfo.setText("jLabel12");

        edtRoleInfo.setText("jLabel12");

        jLabel11.setText("Position");

        edtPosition.setText("jLabel12");

        jLabel12.setText("Ma Phong");

        edtMaphong.setText("jLabel14");

        jLabel14.setText("Ma Ho So");

        edtMahs.setText("jLabel16");

        jLabel16.setText("Ma Nhan Vien");

        edtManv.setText("jLabel17");

        javax.swing.GroupLayout jb5Layout = new javax.swing.GroupLayout(jb5);
        jb5.setLayout(jb5Layout);
        jb5Layout.setHorizontalGroup(
            jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jb5Layout.createSequentialGroup()
                .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jb5Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(AvatarImg1))
                    .addGroup(jb5Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(129, 129, 129)
                .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jb5Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel10))
                    .addGroup(jb5Layout.createSequentialGroup()
                        .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(60, 60, 60)
                        .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtManv)
                            .addComponent(edtMahs)
                            .addComponent(edtMaphong)
                            .addComponent(edtPosition)
                            .addComponent(edtUsernameInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtRoleInfo))))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jb5Layout.setVerticalGroup(
            jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jb5Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AvatarImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jb5Layout.createSequentialGroup()
                        .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(edtManv))
                        .addGap(18, 18, 18)
                        .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(edtUsernameInfo))
                        .addGap(25, 25, 25)
                        .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(edtRoleInfo))))
                .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jb5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jb5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(edtPosition))))
                .addGap(12, 12, 12)
                .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(edtMaphong))
                .addGap(29, 29, 29)
                .addGroup(jb5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(edtMahs))
                .addContainerGap(443, Short.MAX_VALUE))
        );

        jb1.setBackground(new java.awt.Color(255, 102, 255));

        jLabel4.setText("HOMEPAGE AE CHÈN ẢNH HAY GÌ VÀO ĐỠ TRỐNG NHÉ");

        javax.swing.GroupLayout jb1Layout = new javax.swing.GroupLayout(jb1);
        jb1.setLayout(jb1Layout);
        jb1Layout.setHorizontalGroup(
            jb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jb1Layout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jb1Layout.setVerticalGroup(
            jb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jb1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(470, Short.MAX_VALUE))
        );

        jb2.setBackground(new java.awt.Color(0, 102, 102));

        jbTableRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbTableRoomMouseClicked(evt);
            }
        });

        jtableRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ma phong", "Ten phong", "Truong phong", "So luong"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtableRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableRoomMouseClicked(evt);
            }
        });
        jbTableRoom.setViewportView(jtableRoom);

        edtSearchRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSearchRoomActionPerformed(evt);
            }
        });

        btnSearchDepartment.setText("Tim Kiem");
        btnSearchDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDepartmentActionPerformed(evt);
            }
        });

        btnAddRoom.setText("Them");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        btnDeleteRoom.setText("Xoa");

        btnUpdateRoom.setText("Sua");

        javax.swing.GroupLayout jb2Layout = new javax.swing.GroupLayout(jb2);
        jb2.setLayout(jb2Layout);
        jb2Layout.setHorizontalGroup(
            jb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbTableRoom)
            .addGroup(jb2Layout.createSequentialGroup()
                .addGroup(jb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jb2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel17))
                    .addGroup(jb2Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(edtSearchRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(btnSearchDepartment))
                    .addGroup(jb2Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(btnAddRoom)
                        .addGap(114, 114, 114)
                        .addComponent(btnDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(btnUpdateRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jb2Layout.setVerticalGroup(
            jb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jb2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtSearchRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jbTableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel17)
                .addGap(27, 27, 27)
                .addGroup(jb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        jb3.setBackground(new java.awt.Color(51, 255, 153));

        jLabel5.setText("AE THÊM BẢNG CÓ NHỮNG THUỘC TÍNH SINH VIÊN VÀO NHÉ");

        javax.swing.GroupLayout jb3Layout = new javax.swing.GroupLayout(jb3);
        jb3.setLayout(jb3Layout);
        jb3Layout.setHorizontalGroup(
            jb3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jb3Layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jb3Layout.setVerticalGroup(
            jb3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jb3Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(500, Short.MAX_VALUE))
        );

        jb4.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jb4Layout = new javax.swing.GroupLayout(jb4);
        jb4.setLayout(jb4Layout);
        jb4Layout.setHorizontalGroup(
            jb4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1109, Short.MAX_VALUE)
        );
        jb4Layout.setVerticalGroup(
            jb4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );

        jb6.setBackground(new java.awt.Color(255, 102, 102));

        jTableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ma Nhan Vien", "Ho Va Ten", "Gioi Tinh", "Ngay Sinh", "So Dien Thoai", "Dia Chi", "Vi Tri", "Ma Phong", "Ma Ho So"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEmployee);

        btnAddEmployee.setText("Them");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });

        btnXoaEmployee.setText("Xoa");
        btnXoaEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaEmployeeActionPerformed(evt);
            }
        });

        btnUpdateEmployee.setText("Sua");
        btnUpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEmployeeActionPerformed(evt);
            }
        });

        btnSearchEmployee.setText("Tim Kiem");
        btnSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jb6Layout = new javax.swing.GroupLayout(jb6);
        jb6.setLayout(jb6Layout);
        jb6Layout.setHorizontalGroup(
            jb6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jb6Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(edtSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(btnSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(388, Short.MAX_VALUE))
            .addGroup(jb6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddEmployee)
                .addGap(66, 66, 66)
                .addComponent(btnXoaEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnUpdateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(356, 356, 356))
        );
        jb6Layout.setVerticalGroup(
            jb6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jb6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jb6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 385, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jb6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jb6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(244, 244, 244))
        );

        jbAddEmployee.setBackground(new java.awt.Color(153, 153, 153));

        jLabel18.setText("Ma Nhan Vien");

        jLabel19.setText("Ho Va Ten");

        jLabel20.setText("Gioi Tinh");

        jLabel21.setText("Ngay Sinh");

        jLabel22.setText("So Dien Thoai");

        jLabel23.setText("Dia Chi");

        jLabel24.setText("Vi Tri");

        jLabel25.setText("Ma Phong");

        jLabel26.setText("Ma Ho So");

        buttonGroup1.add(jRadioNam);
        jRadioNam.setText("Nam");

        buttonGroup1.add(jRadioNu);
        jRadioNu.setText("Nu");

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jbAddEmployeeLayout = new javax.swing.GroupLayout(jbAddEmployee);
        jbAddEmployee.setLayout(jbAddEmployeeLayout);
        jbAddEmployeeLayout.setHorizontalGroup(
            jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbAddEmployeeLayout.createSequentialGroup()
                .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jbAddEmployeeLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(119, 119, 119)
                        .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtManvEmployee)
                            .addComponent(edtFullName)
                            .addComponent(edtBirthday)
                            .addComponent(edtPhone)
                            .addComponent(edtAddress)
                            .addComponent(edtPositionEmployee)
                            .addComponent(edtMaphongEmployee)
                            .addComponent(edtMahsEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jbAddEmployeeLayout.createSequentialGroup()
                                .addComponent(jRadioNam)
                                .addGap(45, 45, 45)
                                .addComponent(jRadioNu))))
                    .addGroup(jbAddEmployeeLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jbAddEmployeeLayout.setVerticalGroup(
            jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbAddEmployeeLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jbAddEmployeeLayout.createSequentialGroup()
                        .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(edtManvEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(edtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel20)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel21))
                    .addGroup(jbAddEmployeeLayout.createSequentialGroup()
                        .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioNam)
                            .addComponent(jRadioNu))
                        .addGap(18, 18, 18)
                        .addComponent(edtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(edtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(edtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(edtPositionEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(edtMaphongEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(edtMahsEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jbAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightPanelLayout.createSequentialGroup()
                    .addComponent(jb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jb4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jb5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                    .addComponent(jb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jb4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightPanelLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jb5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(7, 7, 7)))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        // TODO add your handling code here:
        jb1.setVisible(true);
        jb2.setVisible(false);
        jb3.setVisible(false);
        jb4.setVisible(false);
        jb5.setVisible(false);
        jb6.setVisible(false);
        jbAddEmployee.setVisible(false);
        tab1.setBackground(Color.gray);
        tab2.setBackground(new Color(102, 102, 102));
        tab3.setBackground(new Color(102, 102, 102));
        tab4.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        // TODO add your handling code here:
        jb1.setVisible(false);
        jb2.setVisible(true);
        jb3.setVisible(false);
        jb4.setVisible(false);
        jb5.setVisible(false);
        jb6.setVisible(false);
        jbAddEmployee.setVisible(false);
        tab2.setBackground(Color.gray);
        tab1.setBackground(new Color(102, 102, 102));
        tab3.setBackground(new Color(102, 102, 102));
        tab4.setBackground(new Color(102, 102, 102));
        tableModel = (DefaultTableModel) jtableRoom.getModel();
        showRoom();
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        // TODO add your handling code here:
        jb1.setVisible(false);
        jb2.setVisible(false);
        jb3.setVisible(true);
        jb4.setVisible(false);
        jb5.setVisible(false);
        jb6.setVisible(false);
        jbAddEmployee.setVisible(false);
        tab3.setBackground(Color.gray);
        tab2.setBackground(new Color(102, 102, 102));
        tab1.setBackground(new Color(102, 102, 102));
        tab4.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        // TODO add your handling code here:
        jb1.setVisible(false);
        jb2.setVisible(false);
        jb3.setVisible(false);
        jb4.setVisible(true);
        jb5.setVisible(false);
        jb6.setVisible(false);
        jbAddEmployee.setVisible(false);
        tab4.setBackground(Color.gray);
        tab2.setBackground(new Color(102, 102, 102));
        tab3.setBackground(new Color(102, 102, 102));
        tab1.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_tab4MouseClicked

    private void edtSearchRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSearchRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtSearchRoomActionPerformed

    private void AvatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AvatarMouseClicked
        // TODO add your handling code here:
        jb1.setVisible(false);
        jb2.setVisible(false);
        jb3.setVisible(false);
        jb4.setVisible(false);
        jb5.setVisible(true);
        jb6.setVisible(false);
        jbAddEmployee.setVisible(false);
    }//GEN-LAST:event_AvatarMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        dispose();
        loginForm log = new loginForm();
        log.show();
    }//GEN-LAST:event_logoutMouseClicked

    private void jbTableRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTableRoomMouseClicked

    }//GEN-LAST:event_jbTableRoomMouseClicked

    private void jtableRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableRoomMouseClicked
        // TODO add your handling code here:
        // set data to their textfield
        tableModel = (DefaultTableModel) jtableRoom.getModel();
        // set data to text field when row is selected
        String tblMaphong = tableModel.getValueAt(jtableRoom.getSelectedRow(), 0).toString();
        if (jtableRoom.getSelectedRowCount() == 1) {
            jb6.setVisible(true);
            jb1.setVisible(false);
            jb2.setVisible(false);
            jb3.setVisible(false);
            jb4.setVisible(false);
            jb5.setVisible(false);
            jbAddEmployee.setVisible(false);
            tableModel = (DefaultTableModel) jTableEmployee.getModel();
            showEmplyeeByMaPhong(tblMaphong);
        }
    }//GEN-LAST:event_jtableRoomMouseClicked

    private void btnSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEmployeeActionPerformed
        // TODO add your handling code here:
        String edtSearch = edtSearchEmployee.getText();
        searchEmployeee(edtSearch);
    }//GEN-LAST:event_btnSearchEmployeeActionPerformed

    private void btnSearchDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDepartmentActionPerformed
        // TODO add your handling code here:
        String edtSearch = edtSearchRoom.getText();
        searchDepartment(edtSearch);
    }//GEN-LAST:event_btnSearchDepartmentActionPerformed

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
        if ("ADMIN".equals(role) || "MANAGE".endsWith(role)) {
            btnSua.setVisible(false);
            btnThem.setVisible(true);
            jbAddEmployee.setVisible(true);
            jb6.setVisible(false);
            jb1.setVisible(false);
            jb2.setVisible(false);
            jb3.setVisible(false);
            jb4.setVisible(false);
            jb5.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có thẩm quyền này!");
        }
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnUpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEmployeeActionPerformed
        // TODO add your handling code here:
        if ("ADMIN".equals(role) || "MANAGE".endsWith(role)) {
            btnThem.setVisible(false);
            btnSua.setVisible(true);
            jb6.setVisible(false);
            jb1.setVisible(false);
            jb2.setVisible(false);
            jb3.setVisible(false);
            jb4.setVisible(false);
            jb5.setVisible(false);
            jbAddEmployee.setVisible(true);
            // set data to their textfield
            DefaultTableModel tblModel = (DefaultTableModel) jTableEmployee.getModel();
            // set data to text field when row is selected
            if (jTableEmployee.getSelectedRowCount() == 1) {
                edtManvEmployee.setText(tblModel.getValueAt(jTableEmployee.getSelectedRow(), 0).toString());
                edtFullName.setText(tblModel.getValueAt(jTableEmployee.getSelectedRow(), 1).toString());
                edtBirthday.setText(tblModel.getValueAt(jTableEmployee.getSelectedRow(), 3).toString());
                edtPhone.setText(tblModel.getValueAt(jTableEmployee.getSelectedRow(), 4).toString());
                edtAddress.setText(tblModel.getValueAt(jTableEmployee.getSelectedRow(), 5).toString());
                edtPositionEmployee.setText(tblModel.getValueAt(jTableEmployee.getSelectedRow(), 6).toString());
                edtMaphongEmployee.setText(tblModel.getValueAt(jTableEmployee.getSelectedRow(), 7).toString());
                edtMahsEmployee.setText(tblModel.getValueAt(jTableEmployee.getSelectedRow(), 8).toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có thẩm quyền này!");
        }
    }//GEN-LAST:event_btnUpdateEmployeeActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if ("ADMIN".equals(role) || "MANAGE".endsWith(role)) {
            if (checkForm() == false) {
                JOptionPane.showMessageDialog(this, "Nhập thiếu ");
            } else {
                String manv = edtManvEmployee.getText();
                String fullName = edtFullName.getText();
                String birthday = edtBirthday.getText();
                int phone = Integer.parseInt(edtPhone.getText());
                String address = edtAddress.getText();
                String position = edtPositionEmployee.getText();
                String maPhong = edtMaphongEmployee.getText();
                String maHoSo = edtMahsEmployee.getText();
                employeeModel model = new employeeModel(manv, fullName, "Nam", birthday, phone, address, position, maPhong, maHoSo);
                employeeController nv = new employeeController();
                nv.addEmployee(model);
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                edtManvEmployee.setText("");
                edtFullName.setText("");
                edtBirthday.setText("");
                edtPhone.setText("");
                edtAddress.setText("");
                edtPositionEmployee.setText("");
                edtMaphongEmployee.setText("");
                edtMahsEmployee.setText("");
                showEmplyeeByMaPhong(maPhong);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có thẩm quyền này!");
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jb6.setVisible(true);
        jb1.setVisible(false);
        jb2.setVisible(false);
        jb3.setVisible(false);
        jb4.setVisible(false);
        jb5.setVisible(false);
        jbAddEmployee.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if ("ADMIN".equals(role) || "MANAGE".endsWith(role)) {
            if (checkForm() == false) {
                JOptionPane.showMessageDialog(this, "Nhập thiếu ");
            } else {
                String manv = edtManvEmployee.getText();
                String fullName = edtFullName.getText();
                String birthday = edtBirthday.getText();
                int phone = Integer.parseInt(edtPhone.getText());
                String address = edtAddress.getText();
                String position = edtPositionEmployee.getText();
                String maPhong = edtMaphongEmployee.getText();
                String maHoSo = edtMahsEmployee.getText();
                employeeModel model = new employeeModel(manv, fullName, "Nam", birthday, phone, address, position, maPhong, maHoSo);
                employeeController nv = new employeeController();

                nv.updateEmployee(model);
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                showEmplyeeByMaPhong(maPhong);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có thẩm quyền này!");
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaEmployeeActionPerformed
        // TODO add your handling code here:
        if ("ADMIN".equals(role) || "MANAGE".endsWith(role)) {
            DefaultTableModel tblModel = (DefaultTableModel) jTableEmployee.getModel();
            String manv = tblModel.getValueAt(jTableEmployee.getSelectedRow(), 0).toString();
            String maphong = tblModel.getValueAt(jTableEmployee.getSelectedRow(), 7).toString();
            if (jTableEmployee.getSelectedRowCount() == 1) {
                int option = JOptionPane.showConfirmDialog(this, "Ban co muon xoa phong nay ?");
                if (option == 0) {
                    employeeController empl = new employeeController();
                    empl.deleteEmployee(manv);
                }

            }
            showEmplyeeByMaPhong(maphong);
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có thẩm quyền này!");
        }

    }//GEN-LAST:event_btnXoaEmployeeActionPerformed

    public void showRoom() {
        ListRoom = departmentController.getRoom();
        tableModel.setRowCount(0);
        ListRoom.forEach((departmentModel) -> {
            tableModel.addRow(new Object[]{
                departmentModel.getMaphong(),
                departmentModel.getTenphong(),
                departmentModel.getLeader()
            });
        });
        tableModel.fireTableDataChanged();
    }

    public void showEmplyeeByMaPhong(String maphong) {
        ListEmployee = employeeController.getEmployByMaPhong(maphong);
        tableModel.setRowCount(0);
        ListEmployee.forEach((employeeModel) -> {
            tableModel.addRow(new Object[]{
                employeeModel.getManv(),
                employeeModel.getFullname(),
                employeeModel.getSex(),
                employeeModel.getBirthday(),
                employeeModel.getPhoneNumber(),
                employeeModel.getAddress(),
                employeeModel.getPosition(),
                employeeModel.getMaphong(),
                employeeModel.getMahoso()
            });
        });
        tableModel.fireTableDataChanged();
    }

    public void searchDepartment(String edtSearch) {
        tableModel = (DefaultTableModel) jtableRoom.getModel();
        TableRowSorter<DefaultTableModel> tableSort = new TableRowSorter<>(tableModel);
        jTableEmployee.setRowSorter(tableSort);
        tableSort.setRowFilter(RowFilter.regexFilter("(?i)" + edtSearch));
    }

    public void searchEmployeee(String edtSearch) {
        tableModel = (DefaultTableModel) jTableEmployee.getModel();
        TableRowSorter<DefaultTableModel> tableSort = new TableRowSorter<>(tableModel);
        jTableEmployee.setRowSorter(tableSort);
        tableSort.setRowFilter(RowFilter.regexFilter("(?i)" + edtSearch));
    }

    public boolean checkForm() {
        if (edtManvEmployee.getText().isEmpty() || edtFullName.getText().isEmpty()
                || edtBirthday.getText().isEmpty() || edtPhone.getText().isEmpty()
                || edtAddress.getText().isEmpty() || edtPosition.getText().isEmpty()
                || edtMaphongEmployee.getText().isEmpty() || edtMahsEmployee.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Avatar;
    private javax.swing.JLabel AvatarImg;
    private javax.swing.JLabel AvatarImg1;
    private javax.swing.JPanel Notice;
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnDeleteRoom;
    private javax.swing.JButton btnSearchDepartment;
    private javax.swing.JButton btnSearchEmployee;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdateEmployee;
    private javax.swing.JButton btnUpdateRoom;
    private javax.swing.JButton btnXoaEmployee;
    private javax.swing.JPanel btn_Logout;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField edtAddress;
    private javax.swing.JTextField edtBirthday;
    private javax.swing.JTextField edtFullName;
    private javax.swing.JLabel edtMahs;
    private javax.swing.JTextField edtMahsEmployee;
    private javax.swing.JLabel edtManv;
    private javax.swing.JTextField edtManvEmployee;
    private javax.swing.JLabel edtMaphong;
    private javax.swing.JTextField edtMaphongEmployee;
    private javax.swing.JTextField edtPhone;
    private javax.swing.JLabel edtPosition;
    private javax.swing.JTextField edtPositionEmployee;
    private javax.swing.JLabel edtRoleInfo;
    private javax.swing.JTextField edtSearchEmployee;
    private javax.swing.JTextField edtSearchRoom;
    private javax.swing.JLabel edtUsernameHome;
    private javax.swing.JLabel edtUsernameInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLable14;
    private javax.swing.JLabel jLable4;
    private javax.swing.JLabel jLable8;
    private javax.swing.JRadioButton jRadioNam;
    private javax.swing.JRadioButton jRadioNu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmployee;
    private javax.swing.JPanel jb1;
    private javax.swing.JPanel jb2;
    private javax.swing.JPanel jb3;
    private javax.swing.JPanel jb4;
    private javax.swing.JPanel jb5;
    private javax.swing.JPanel jb6;
    private javax.swing.JPanel jbAddEmployee;
    private javax.swing.JScrollPane jbTableRoom;
    private javax.swing.JTable jtableRoom;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    // End of variables declaration//GEN-END:variables
}
